import textwrap
from crewai import Task
from agents.content_writer import content_writer_agent
from tasks.ai_strategy_task import ai_strategy_task
from test_mode import TEST_MODE

# NOTE: Context is [ai_strategy_task] only — the most complete synthesis.

# ── TEST_MODE prompt ──────────────────────────────────────────────────────────
# The writer is asked to produce two tiny files using FileWriterTool.
# Both files will contain placeholder-quality bullet-point content.
_desc_test = textwrap.dedent("""
    Write two minimal markdown files for {company} using FileWriterTool.

    FILE 1 — save as: final_report.md
    Content (write exactly this structure, fill in with 1-sentence answers):
    # Report: {company}
    ## Research
    - [1 fact about the company]
    - [1 fact about the company]
    ## Challenges
    - [1 challenge]
    - [1 challenge]
    ## AI Solutions
    - [1 AI solution]
    - [1 AI solution]

    FILE 2 — save as: ceo_pitch.md
    Content (write exactly this structure):
    # CEO Pitch: {company}
    - We researched {company}.
    - Key challenge: [1 sentence]
    - Recommended action: [1 sentence]

    Each file must be under 100 words.
    Use FileWriterTool twice: once for final_report.md, once for ceo_pitch.md.
""")

_expected_test = textwrap.dedent("""
    Two files saved via FileWriterTool:
    1. final_report.md — minimal bullet-point report, under 100 words
    2. ceo_pitch.md — minimal 3-line pitch, under 50 words
""")

# ── PRODUCTION prompt ─────────────────────────────────────────────────────────
_desc_prod = textwrap.dedent("""
    Produce the final deliverable for: **{company}**

    You have access to three report files via FileWriterTool:
    - research_findings.md
    - analysis_report.md
    - ai_strategy_report.md

    Synthesise them into two crisp, professional outputs.

    ---

    ## OUTPUT 1: FULL BUSINESS INTELLIGENCE REPORT (save to final_report.md)

    Structure:

    # Company Intelligence Report: {company}
    *Generated by AI Company Intelligence System*

    # Executive Summary
    [3 paragraphs: who they are, key challenges, AI transformation opportunity]

    # Company Overview
    [Concise company profile with a formatted info table]

    # Business Intelligence
    ## Revenue & Business Model
    [Key revenue drivers and business model — use a table]
    ## Competitive Position
    [Top competitors and SWOT — use tables]

    # Recent Developments
    [Table: Date | Development | Impact — minimum 4 rows]

    # Business Challenges
    [For each of the 6 challenges — use a compact table format:]
    ## Challenge [N]: [Title]
    | Field | Details |
    |-------|---------|
    | Category | ... |
    | Challenge | ... |
    | Evidence | ... |
    | Impact | ... |
    | Confidence | X/10 |

    # AI Opportunities & Recommended Solutions
    ## AI Transformation Overview
    [1 paragraph on the overall opportunity]
    ## Strategic Roadmap
    [Paste the roadmap table from the strategy report]
    [For each AI opportunity — compact table:]
    ## Solution [N]: [Title]
    | Field | Details |
    |-------|---------|
    | Solution | ... |
    | Tech Stack | ... |
    | Timeline | ... |
    | ROI Estimate | ... |
    | Business Impact | ... |

    # Sources
    [Numbered list of all cited sources]

    ---

    REQUIREMENTS:
    1. Target 1500-2000 words — do NOT pad or repeat
    2. All tables must be properly formatted markdown
    3. Do NOT include a CEO Pitch section in this file
    4. Save using FileWriterTool with filename: final_report.md

    ---

    ## OUTPUT 2: CEO PITCH (save to ceo_pitch.md)

    Write a crisp one-page consulting pitch to the CEO of {company}.

    **Dear [CEO Name],**

    ## Why I Researched {company}
    [1 paragraph — specific, shows you understand their business]

    ## Key Observations
    [3 bullet points — specific, evidence-backed insights]

    ## The 3 Challenges I'd Prioritise
    [3 most critical challenges framed as business problems]

    ## AI Opportunities That Can Transform {company}
    [Top 3 opportunities framed as business value, not technology]

    ## Recommended Next Steps
    [3 specific actions the CEO can take in the next 30 days]

    *Respectfully submitted,*
    *AI Company Intelligence System*

    ---
    Save using FileWriterTool with filename: ceo_pitch.md
    Target 400-500 words. Personalised. No generic statements.
""")

_expected_prod = textwrap.dedent("""
    Two markdown files saved via FileWriterTool:

    1. final_report.md — Business Intelligence Report (1500-2000 words)
       All sections complete with tables. No CEO pitch section.

    2. ceo_pitch.md — Standalone CEO pitch (400-500 words)
       Personalised, specific, no repetition from the main report.
""")

writing_task = Task(
    agent=content_writer_agent,
    description=_desc_test if TEST_MODE else _desc_prod,
    expected_output=_expected_test if TEST_MODE else _expected_prod,
    context=[ai_strategy_task],
    output_file="final_report.md",
)
